language: node_js

node_js:
  - 11

cache:
  directories:
    - $HOME/.npm

stages:
  - test
  - name: deploy
    if: env(BUILD_TYPE) = release

jobs:
  include:
  - stage: test
    script: npm test
  - stage: deploy
    script: npm run build
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      local_dir: dist
      on:
        branch: master